### ISSUE TITLE
Check Style

### ISSUE THREAD

**Issue by Shalynishka** [el41n/markup#2]
В файле 0001_initial.py, расположенном в "markup/src/back-end/editor/migrations/" директории присутствуют строки кода, превышающие максимально допустимую длину, установленную PEP стандартом. 
Также в данном файле отсутствует newline в конце файла, что также противоречит стандарту. Следует отметить, что подобная ошибка присутствует и в других файлах, например, markup/src/back-end/manage.py.

**Comment by el41n** [comment]
Это файлы миграций базы данных. Эти файлы стоит добавить в исключеня
